jobs:
  include:
    - language: python
      python:
        - "3.9"
      install:
        - pip install -e .
      script:
        - python3 -m unittest discover -p "*_test.py"

    - language: go
      install:
          - cd ./peerprint/server && GO111MODULE=on go install ./...
      before_script:
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
          - cd ./peerprint/server && go build .
      script:
          - golangci-lint run       # run a bunch of code checkers/linters in parallel
          - cd ./peerprint/server && go test -v -race ./...  # Run all the tests with the race detector enabled
