language: python
python:
  - "3.9"
install:
  - pip install -e .[tests,dev]
script:
  - python -m unittest discover -p "*_test.py"

before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
language: go
script:
    - golangci-lint run       # run a bunch of code checkers/linters in parallel
    - cd ./peerprint/server && go test -v -race ./...  # Run all the tests with the race detector enabled
