version: '2.4'

x-base: &base
  build: 
    context: .
  command: python3 -m peerprint.server --debug --base_dir=/volume
  ports:
    - "8336:8334" # status http server
    - "8002:8000" # example webserver
  volumes:
    - "/tmp:/tmp" #enable IPC comms for debugging

services:
  dev:
    build: 
      context: .
    command: /bin/bash
    ports:
      - "8336:8334" # status http server
      - "8002:8000" # example webserver
    volumes:
      - "./:/volume"
      - "/tmp:/tmp"
    working_dir: "/volume"
  devhost:
    build: 
      context: .
    command: /bin/bash
    network_mode: host
    volumes:
      - "./:/volume"
      - "/tmp:/tmp"
    working_dir: "/volume"
  server1:
    <<: *base
    ports:
      - "8334:8334" # status http server
      - "8000:8000" # example webserver
    volumes: 
      - "./:/peerprint"
  server2:
    <<: *base
    ports:
      - "8335:8334" # status http server
      - "8001:8000" # example webserver
    volumes: 
      - "./:/peerprint"
  cli:
    <<: *base
    command: python3 -m peerprint.cli --base_dir=/volume
    profiles:
      - "cli1"
  test:
    <<: *base
    command: python -m unittest discover -s peerprint -p "*_test.py"
    profiles:
      - "test"
