version: '2.4'

x-base: &base
  build: 
    context: .
  command: python3 -m peerprint.server --debug --base_dir=/volume
  volumes:
    - "/tmp:/tmp" #enable IPC comms for debugging

services:
  dev:
    build: 
      context: .
    command: /bin/bash
    volumes:
      - "./:/volume"
    working_dir: "/volume"
  server1:
    <<: *base
    volumes: 
      - "./peerprint/networking/testdata/server1/:/volume"
  server2:
    <<: *base
    volumes: 
      - "./peerprint/networking/testdata/server2/:/volume"
  cli:
    <<: *base
    command: python3 -m peerprint.cli --base_dir=/volume
    profiles:
      - "cli1"
  test:
    <<: *base
    command: python -m unittest discover -s peerprint -p "*_test.py"
    profiles:
      - "test"
