eth_queue:
  user: 
    # Wallet address for payment / user recognition
    account: '0x15736104F071b1dCac74a55548b299f3fD78BF27'

    # Encrypted with gpg -ac --no-symkey-cache eth.txt
    keyfile: 'eth.txt.asc'

  service:
    # Address on Goerli test network                                                
    # See https://goerli.etherscan.io/address/0xa02368deb11516d04ec48ddf28b9d181483c4f09
    # For deployment, see https://www.quicknode.com/guides/vyper/how-to-write-an-ethereum-smart-contract-using-vyper
    contract: '0xbc19b66a61c81735bf43c17e13e10c5b7634ba90'

    # Include your API key here - copy from https://dashboard.alchemyapi.io/ > View Key > HTTPS
    provider: "https://eth-goerli.alchemyapi.io/v2/3lKws79pxrssRHoPzIza3UU9ygQwqPgI"

    # ABI of the EthQueue contract
    abi: '[{"name": "Job", "inputs": [], "anonymous": false, "type": "event"}, {"stateMutability": "nonpayable", "type": "constructor", "inputs": [], "outputs": []}, {"stateMutability": "payable", "type": "function", "name": "postJob", "inputs": [{"name": "compat", "type": "bytes32"}, {"name": "content_uri", "type": "string"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "revokeJob", "inputs": [{"name": "jid", "type": "bytes32"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "acquireJob", "inputs": [{"name": "jid", "type": "bytes32"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "releaseJob", "inputs": [{"name": "jid", "type": "bytes32"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "completeJob", "inputs": [{"name": "jid", "type": "bytes32"}], "outputs": []}]' 
